### ISSUE TITLE
`EFI::UNEXPECTED_ERROR` when `blkid -p -s PART_ENTRY_NUMBER` is empty

### ISSUE THREAD

**Issue by BradLugo** [oamg/convert2rhel#1167]
Hello Conversions team!

I'm running into an issue when calling `convert2rhel analyze` on a Rocky 8 system that's using mdadm. In particular, there seems to be a problem during the `Check the firmware interface type (BIOS/UEFI)`:

```
[2024-04-03T06:46:53+0200] TASK - [Prepare: Check the firmware interface type (BIOS/UEFI)] ***********
UEFI detected.
[2024-04-03T06:46:53+0200] DEBUG - Calling command 'mokutil --sb-state'
[2024-04-03T06:46:53+0200] DEBUG - Calling command '/usr/sbin/efibootmgr -v'
[2024-04-03T06:46:53+0200] DEBUG - Bootloader setup:
Current boot: 0004
Boot order: 0000, 0003, 0004, 0005, 0006, 0001
Boot entries:
- 0000: Rocky Linux
- 0001: UEFI: Built-in EFI Shell
- 0003: UEFI: PXE IP4 P0 Intel(R) I210 Gigabit  Network Connection
- 0004: UEFI OS
- 0005: UEFI OS
- 0006: UEFI OS
[2024-04-03T06:46:53+0200] DEBUG - Calling command '/usr/sbin/grub2-probe --target=device /boot/efi/'
[2024-04-03T06:46:53+0200] DEBUG - Calling command '/usr/sbin/blkid -p -s PART_ENTRY_NUMBER /dev/md0'
ERROR - (ERROR) EFI::UNEXPECTED_ERROR - Unhandled exception caught
 Description: Unhandled exception was caught: invalid literal for int() with base 10: '\n'
Please file a bug at https://issues.redhat.com/ to have this fixed or a specific error message added.
Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/actions/__init__.py", line 572, in run
    action.run()
  File "/usr/lib/python3.6/site-packages/convert2rhel/actions/system_checks/efi.py", line 74, in run
    grub.get_device_number(grub.get_efi_partition())
  File "/usr/lib/python3.6/site-packages/convert2rhel/grub.py", line 178, in get_device_number
    return int(partition_number)
ValueError: invalid literal for int() with base 10: '\n'

 Diagnosis: N/A
 Remediations: N/A

EUS_SYSTEM_CHECK has succeeded
```

Admittedly, I didn't configure the software RAID myself, so maybe this is user error? Interested in any insight yall have. Also happy to help debug or submit a PR after figuring out what the problem is 🙂

**Comment by BradLugo** [comment]
This seems to be the cause (specifically the `int(partition_number)` toward the bottom):
https://github.com/oamg/convert2rhel/blob/985cf347ffd0e172c53fb44d6c50340c3f765b20/convert2rhel/grub.py#L156-L178

I'm not *too* familiar with these lower-level details (trying to get better 😄), but I'm also having a difficult time figuring out what we might use the partition entry number for since the caller doesn't give any hints (at least, not with my current understanding):
https://github.com/oamg/convert2rhel/blob/985cf347ffd0e172c53fb44d6c50340c3f765b20/convert2rhel/actions/system_checks/efi.py#L70-L83

**Comment by bocekm** [comment]
I'd say this is not resolved. With @1169 convert2rhel does not traceback but still provides just a more graceful error message. The problem seems to be that we can't handle RAID+UEFI. A similar issue has been reported under https://github.com/oamg/convert2rhel/issues/1247. Let's continue tracking the problem there.
