### ISSUE TITLE
Exception on Alma/Rocky 8.9

### ISSUE THREAD

**Issue by Palando** [oamg/convert2rhel#1178]
I got the following python exception on AlmaLinux 8.9 and Rocky Linux 8.9 (with my correct RH credentials):

```bash
[root@rhel-build-04 ~]# convert2rhel analyze -u "************@***.de" -p "********"
Traceback (most recent call last):
  File "/usr/bin/convert2rhel", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/convert2rhel", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/convert2rhel", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'convert2rhel==1.7.1' distribution was not found and is required by the application
```

I installed the last release as RPM. May be there is a missing dependency?

**Comment by Palando** [comment]
Sry, I used the wrong RPM (for RH9 instead of RH8).

**Comment by Palando** [comment]
Sry, I used the wrong RPM (for RH9 instead of RH8).
