### ISSUE TITLE
CentOS 8.3 -> RHEL

### ISSUE THREAD

**Issue by Eli-Tarrago** [oamg/convert2rhel#145]
Default server image used in an openstack environment. Converting a fully update to date CentOS 8 server to RHEL. It seems the code gets stuck on #143 in that it is not able to fetch the /etc/system-release because the utility relocates it. 

```

rpm -qa | grep convert
convert2rhel-0.15-1.el8.noarch

yum repolist
repo id                                                                                         repo name
appstream                                                                                       CentOS Linux 8 - AppStream
baseos                                                                                          CentOS Linux 8 - BaseOS
extras                                                                                          CentOS Linux 8 - Extras

convert2rhel --disable-submgr --enablerepo appstream --enablerepo baseos --debug

WARNING - By continuing you accept this EULA.



[01/12/2021 09:14:52] TASK - [Prepare: Gather system information] *******************************
Name:                CentOS Release
OS major version:    8
[01/12/2021 09:14:52] DEBUG - Calling command 'uname -i'
Architecture:        x86_64
Config filename:     centos-8-x86_64.cfg
Running the 'rpm -Va' command which can take several minutes. It can be disabled by using the --no-rpm-va option.
[01/12/2021 09:14:52] DEBUG - Calling command 'rpm -Va'
The 'rpm -Va' output has been stored in the /var/log/convert2rhel/rpm_va.log file

[01/12/2021 09:15:04] TASK - [Prepare: Determine RHEL variant] **********************************
Variant: Server

[01/12/2021 09:15:04] TASK - [Prepare: Backup System] *******************************************
Backing up /etc/system-release
Copying /etc/system-release to /var/lib/convert2rhel/
Backing up /etc/yum.conf
Copying /etc/yum.conf to /var/lib/convert2rhel/

[01/12/2021 09:15:04] TASK - [Prepare: Clear YUM/DNF version locks] *****************************
Usage of YUM/DNF versionlock plugin not detected.

[01/12/2021 09:15:04] TASK - [Convert: Remove excluded packages] ********************************
Searching for the following excluded packages:

centos-logos* ................................... 0
centos-indexhtml ................................ 0
centos*-release ................................. 1
centos*-repos ................................... 1
centos-obsolete-packages ........................ 0
redhat-release* ................................. 0
rhn* ............................................ 1
python3-rhn* .................................... 2


WARNING - The following packages will be removed...
Package                                                                Packager         Repository
-------                                                                --------         ----------
centos-linux-release-8.3-1.2011.el8.noarch                             CentOS Buildsys  @@commandline
centos-linux-repos-8-2.el8.noarch                                      CentOS Buildsys  @@commandline
rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64          CentOS Buildsys  @@commandline
python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64  CentOS Buildsys  @@commandline
python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch              CentOS Buildsys  @@commandline



Backing up centos-linux-release-8.3-1.2011.el8.noarch
[01/12/2021 09:15:09] DEBUG - Downloading the centos-linux-release-8.3-1.2011.el8.noarch package.
[01/12/2021 09:15:09] DEBUG - Calling command 'yumdownloader -v --destdir="/var/lib/convert2rhel/" centos-linux-release-8.3-1.2011.el8.noarch'
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.23
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Thu Jan  7 10:51:09 2021.
repo: using cache for: baseos
baseos: using metadata from Thu Jan  7 10:51:01 2021.
repo: using cache for: extras
extras: using metadata from Thu Nov 12 08:42:22 2020.
Last metadata expiration check: 1:09:56 ago on Tue Jan 12 08:05:14 2021.
Completion plugin: Generating completion cache...
[SKIPPED] centos-linux-release-8.3-1.2011.el8.noarch.rpm: Already downloaded
Successfully downloaded the centos-linux-release-8.3-1.2011.el8.noarch package.
[01/12/2021 09:15:11] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/centos-linux-release-8.3-1.2011.el8.noarch.rpm
Backing up centos-linux-repos-8-2.el8.noarch
[01/12/2021 09:15:11] DEBUG - Downloading the centos-linux-repos-8-2.el8.noarch package.
[01/12/2021 09:15:11] DEBUG - Calling command 'yumdownloader -v --destdir="/var/lib/convert2rhel/" centos-linux-repos-8-2.el8.noarch'
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.23
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Thu Jan  7 10:51:09 2021.
repo: using cache for: baseos
baseos: using metadata from Thu Jan  7 10:51:01 2021.
repo: using cache for: extras
extras: using metadata from Thu Nov 12 08:42:22 2020.
Last metadata expiration check: 1:09:57 ago on Tue Jan 12 08:05:14 2021.
Completion plugin: Generating completion cache...
[SKIPPED] centos-linux-repos-8-2.el8.noarch.rpm: Already downloaded
Successfully downloaded the centos-linux-repos-8-2.el8.noarch package.
[01/12/2021 09:15:12] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/centos-linux-repos-8-2.el8.noarch.rpm
Backing up rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64
[01/12/2021 09:15:12] DEBUG - Downloading the rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 package.
[01/12/2021 09:15:12] DEBUG - Calling command 'yumdownloader -v --destdir="/var/lib/convert2rhel/" rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64'
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.23
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Thu Jan  7 10:51:09 2021.
repo: using cache for: baseos
baseos: using metadata from Thu Jan  7 10:51:01 2021.
repo: using cache for: extras
extras: using metadata from Thu Nov 12 08:42:22 2020.
Last metadata expiration check: 1:09:58 ago on Tue Jan 12 08:05:14 2021.
Completion plugin: Generating completion cache...
[SKIPPED] rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64.rpm: Already downloaded
Successfully downloaded the rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 package.
[01/12/2021 09:15:13] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64.rpm
Backing up python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64
[01/12/2021 09:15:13] DEBUG - Downloading the python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 package.
[01/12/2021 09:15:13] DEBUG - Calling command 'yumdownloader -v --destdir="/var/lib/convert2rhel/" python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64'
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.23
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Thu Jan  7 10:51:09 2021.
repo: using cache for: baseos
baseos: using metadata from Thu Jan  7 10:51:01 2021.
repo: using cache for: extras
extras: using metadata from Thu Nov 12 08:42:22 2020.
Last metadata expiration check: 1:10:00 ago on Tue Jan 12 08:05:14 2021.
Completion plugin: Generating completion cache...
[SKIPPED] python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64.rpm: Already downloaded
Successfully downloaded the python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 package.
[01/12/2021 09:15:14] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64.rpm
Backing up python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch
[01/12/2021 09:15:14] DEBUG - Downloading the python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch package.
[01/12/2021 09:15:14] DEBUG - Calling command 'yumdownloader -v --destdir="/var/lib/convert2rhel/" python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch'
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.23
cachedir: /var/cache/dnf
User-Agent: constructed: 'libdnf (CentOS Linux 8; generic; Linux.x86_64)'
repo: using cache for: appstream
appstream: using metadata from Thu Jan  7 10:51:09 2021.
repo: using cache for: baseos
baseos: using metadata from Thu Jan  7 10:51:01 2021.
repo: using cache for: extras
extras: using metadata from Thu Nov 12 08:42:22 2020.
Last metadata expiration check: 1:10:01 ago on Tue Jan 12 08:05:14 2021.
Completion plugin: Generating completion cache...
[SKIPPED] python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch.rpm: Already downloaded
Successfully downloaded the python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch package.
[01/12/2021 09:15:15] DEBUG - Path of the downloaded package: /var/lib/convert2rhel/python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch.rpm
Removing package: centos-linux-release-8.3-1.2011.el8.noarch
[01/12/2021 09:15:15] DEBUG - Calling command 'rpm -e --nodeps centos-linux-release-8.3-1.2011.el8.noarch'
Removing package: centos-linux-repos-8-2.el8.noarch
[01/12/2021 09:15:16] DEBUG - Calling command 'rpm -e --nodeps centos-linux-repos-8-2.el8.noarch'
Removing package: rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64
[01/12/2021 09:15:16] DEBUG - Calling command 'rpm -e --nodeps rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64'
Removing package: python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64
[01/12/2021 09:15:16] DEBUG - Calling command 'rpm -e --nodeps python3-rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64'
Removing package: python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch
[01/12/2021 09:15:16] DEBUG - Calling command 'rpm -e --nodeps python3-rhnlib-2.8.6-8.module_el8.1.0+211+ad6c0bc7.noarch'
[01/12/2021 09:15:17] DEBUG - Successfully removed 5 packages

[01/12/2021 09:15:17] TASK - [Convert: Install Red Hat release package] *************************
Installing redhat-release package
No package to install

[01/12/2021 09:15:17] TASK - [Convert: Patch yum configuration file] ****************************
[01/12/2021 09:15:17] DEBUG - /etc/yum.conf patched.

[01/12/2021 09:15:17] TASK - [Convert: List third-party packages] *******************************
WARNING - Only packages signed by CentOS Release are to be reinstalled. Red Hat support won't be provided for the following third party packages:

Package                         Packager  Repository
-------                         --------  ----------
convert2rhel-0.15-1.el8.noarch  N/A       @@commandline



WARNING - The tool allows rollback of any action until this point.
WARNING - By continuing all further changes on the system will need to be reverted manually by the user, if necessary.



[01/12/2021 09:16:00] TASK - [Convert: Import Red Hat GPG keys] *********************************
[01/12/2021 09:16:00] DEBUG - Calling command 'rpm --import /usr/share/convert2rhel/gpg-keys/RPM-GPG-KEY-redhat-legacy-release'
[01/12/2021 09:16:00] DEBUG - Calling command 'rpm --import /usr/share/convert2rhel/gpg-keys/RPM-GPG-KEY-redhat-release'

[01/12/2021 09:16:00] TASK - [Convert: Prepare kernel] ******************************************
Installing RHEL kernel ...
[01/12/2021 09:16:00] DEBUG - Calling command 'yum install -y --disablerepo=* --enablerepo=appstream --enablerepo=baseos kernel'
Unable to detect release version (use '--releasever' to specify release version)
Failed loading plugin "spacewalk": No module named 'up2date_client'
Error: Unknown repo: 'appstream'
[01/12/2021 09:16:00] CRITICAL - Error occured while attempting to install the RHEL kernel
[01/12/2021 09:16:00] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 89, in main
    post_ponr_conversion()
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 190, in post_ponr_conversion
    pkghandler.preserve_only_rhel_kernel()
  File "/usr/lib/python3.6/site-packages/convert2rhel/pkghandler.py", line 447, in preserve_only_rhel_kernel
    kernel_update_needed = install_rhel_kernel()
  File "/usr/lib/python3.6/site-packages/convert2rhel/pkghandler.py", line 468, in install_rhel_kernel
    loggerinst.critical("Error occured while attempting to install the"
  File "/usr/lib/python3.6/site-packages/convert2rhel/logger.py", line 105, in critical
    sys.exit(msg)
SystemExit: Error occured while attempting to install the RHEL kernel

WARNING - Conversion process interrupted and manual user intervention will be necessary.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/convert2rhel/main.py", line 55, in main
    toolopts.CLI()
  File "/usr/lib/python3.6/site-packages/convert2rhel/toolopts.py", line 51, in __init__
    self._process_cli_options()
  File "/usr/lib/python3.6/site-packages/convert2rhel/toolopts.py", line 166, in _process_cli_options
    parsed_opts, _ = self._parser.parse_args()
  File "/usr/lib64/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib64/python3.6/optparse.py", line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib64/python3.6/optparse.py", line 808, in take_action
    parser.exit()
  File "/usr/lib64/python3.6/optparse.py", line 1559, in exit
    sys.exit(status)
SystemExit: 0
```

**Comment by Eli-Tarrago** [comment]
I did not have a RHEL's package repo's attached and made available to the vm.
