### ISSUE TITLE
Trying to convert centos8 fails

### ISSUE THREAD

**Issue by ares** [oamg/convert2rhel#187]
Running convert2rhel-0.17-1.el8.noarch on CentOS 8 seems to be failing without using an activation key

After the certificates installation step I'm propmted for the username and password

```
[02/15/2021 19:38:45] TASK - [Convert: Subscription Manager - Subscribe system] *****************                                        
Building subscription-manager command ... 
    ... activation key not found, username and password required
Username: rhn-engineering-mhulan


Password: 


Registering system by running subscription-manager command ... 
Unregistering from: subscription.rhsm.redhat.com:443/subscription
Network error. Please check the connection details, or see /var/log/rhsm/rhsm.log for more information.
System registration failed with return code = 70
Trying again - provide username and password.
Building subscription-manager command ... 
    ... activation key not found, username and password required
```

rhsm log
```
2021-02-15 19:41:21,368 [ERROR] 6:14957:MainThread @connection.py:793 - Response: 400
2021-02-15 19:41:21,368 [ERROR] 6:14957:MainThread @connection.py:794 - JSON parsing error: Expecting value: line 1 column 1 (char 0)
2021-02-15 19:41:21,368 [ERROR] 6:14957:MainThread @managercli.py:218 - Unregister failed
2021-02-15 19:41:21,369 [ERROR] 6:14957:MainThread @managercli.py:219 - HTTP error (400 - Bad Request)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/subscription_manager/managercli.py", line 1547, in _do_command
    unregister.UnregisterService(self.cp).unregister()
  File "/usr/lib64/python3.6/site-packages/rhsmlib/services/unregister.py", line 54, in unregister
    self.uep.unregisterConsumer(self.identity.uuid)
  File "/usr/lib64/python3.6/site-packages/rhsm/connection.py", line 1322, in unregisterConsumer
    return self.conn.request_delete(method)
  File "/usr/lib64/python3.6/site-packages/rhsm/connection.py", line 892, in request_delete
    return self._request("DELETE", method, params, headers=headers)
  File "/usr/lib64/python3.6/site-packages/rhsm/connection.py", line 906, in _request
    info=info, headers=headers, cert_key_pairs=cert_key_pairs)
  File "/usr/lib64/python3.6/site-packages/rhsm/connection.py", line 765, in _request
    self.validateResponse(result, request_type, handler)
  File "/usr/lib64/python3.6/site-packages/rhsm/connection.py", line 863, in validateResponse
    raise NetworkException(response['status'])
rhsm.connection.NetworkException: HTTP error (400 - Bad Request)
```

**Comment by ZhukovGreen** [comment]
Hi @ares thank you for reporting this issue. Could you try to run pass the logging and password in this way:
```
 convert2rhel ---username rhn-engineering-mhulan --password YOUR_PASSWORD --debug
 ```

**Comment by ares** [comment]
it seems my instance had some subscription-manager client certificate in place already, the clean installation seems to be covnerting well. I'll do more investigation and will reopen if I find a good reproducer, perhaps convert2rhel could do some more cleanup (if I identify the cause)
