### ISSUE TITLE
[Convert: Subscription Manager - Subscribe system] UnicodeEncodeError

### ISSUE THREAD

**Issue by HepplerDotNet** [oamg/convert2rhel#367]
Running convert2rhel on my CentOS 8.4.2105 box stops after registering the subscription:
```
[11/13/2021 17:04:17] TASK - [Convert: Subscription Manager - Subscribe system] *****************
Building subscription-manager command ...
    ... activation key not found, using given username and password
    ... username detected
    ... password detected
Registering the system using subscription-manager ...
Registrieren bei: subscription.rhsm.redhat.com:443/subscription
Das System wurde mit ID registriert: e740841c-18fd-4736-a475-114fcf16a0fb
Der registrierte Systemname lautet: localhost
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 205: ordinal not in range(128)
Call stack:
  File "/usr/sbin/subscription-manager", line 11, in <module>
    load_entry_point('subscription-manager==1.28.21', 'console_scripts', 'subscription-manager')()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/scripts/subscription_manager.py", line 87, in main
    return managercli.ManagerCLI().main()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/managercli.py", line 3365, in main
    ret = CLI.main(self)
  File "/usr/lib64/python3.6/site-packages/subscription_manager/cli.py", line 183, in main
    return cmd.main()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/managercli.py", line 564, in main
    return_code = self._do_command()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/managercli.py", line 1741, in _do_command
    self.entcertlib.update()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/certlib.py", line 32, in update
    self.report = self.locker.run(self._do_update)
  File "/usr/lib64/python3.6/site-packages/subscription_manager/certlib.py", line 18, in run
    return action()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/entcertlib.py", line 42, in _do_update
    return action.perform()
  File "/usr/lib64/python3.6/site-packages/subscription_manager/entcertlib.py", line 131, in perform
    log.info('certs updated:\n%s', self.report)
Message: 'certs updated:\n%s'
Arguments: (<subscription_manager.entcertlib.EntCertUpdateReport object at 0x7f0d20f67240>,)
Manually select subscription appropriate for the conversion
CRITICAL - Unable to get list of available subscriptions:
+-------------------------------------------+
'ascii' codec can't encode character '\xfc' in position 8: ordinal not in range(128)

WARNING - Abnormal exit! Performing rollback ...
```

My CentOS is german, so I tried `LC_ALL=C convert2rhel` as workaround (https://access.redhat.com/discussions/6462611), same error. Any idea how to fix?

**Comment by bocekm** [comment]
Hi @HepplerDotNet, thank you for the report and sorry for the inconvenience.

To work around the issue, run `# LANG=C convert2rhel`.

Just for reference, I've filed a Bugzilla for this bug: https://bugzilla.redhat.com/show_bug.cgi?id=2022854.

**Comment by pirat89** [comment]
@HepplerDotNet  just adding, that `LC_ALL` sets all `LC_*` (local collations), but not `LANG`. So ideal is to set both in similar problems just to be sure, e.g. `LC_ALL=C LANG=C convert2rhel` - I mean in general, not just for `convert2rhel`.

**Comment by bocekm** [comment]
@pirat89, it seems it's just the subscription-manager that's misbehaving: https://github.com/oamg/convert2rhel/pull/386#issuecomment-987584120. LC_ALL is supposed to have priority over LANG.

**Comment by pirat89** [comment]
@bocekm actually not. you can try and check output of the `locale` command. You can see, that `LANG` overwritten by the `LC_ALL` setup. So actually RHSM behaves correctly.

**Comment by bocekm** [comment]
Fixed by https://github.com/oamg/convert2rhel/pull/386.
