### ISSUE TITLE
Traceback in check for most recent kernel version

### ISSUE THREAD

**Issue by MaZZly** [oamg/convert2rhel#618]
Version: 1.0
OS: Centos 7 (core)

Running conversion failed, with `--debug` we can see the following:
```
[09/28/2022 06:37:36] DEBUG - Calling command 'repoquery --quiet --qf "%{BUILDTIME}\t%{VERSION}-%{RELEASE}\t%{REPOID}" kernel'
[09/28/2022 06:37:37] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/convert2rhel/main.py", line 94, in main
    checks.perform_pre_checks()
  File "/usr/lib/python2.7/site-packages/convert2rhel/checks.py", line 68, in perform_pre_checks
    is_loaded_kernel_latest()
  File "/usr/lib/python2.7/site-packages/convert2rhel/checks.py", line 661, in is_loaded_kernel_latest
    _, latest_kernel, repoid = packages[0]
ValueError: need more than 1 value to unpack
```

Output of `repoquery --quiet --qf "%{BUILDTIME}\t%{VERSION}-%{RELEASE}\t%{REPOID}" kernel`:
```
Repo convert2rhel-for-rhel-7-rpms forced skip_if_unavailable=True due to: /etc/rhsm/ca/redhat-uep.pem
1660149508	3.10.0-1160.76.1.el7	updates
```

Was easy workaround to edit the tracebacking line to `packages[1]`, but should probably have some sanity check there?

**Comment by SpyTec** [comment]
Hi @MaZZly!

Thanks for reporting this. We've fixed this for v1.1, so currently pending release. There is a note in the known issues section of the product docs about it:
> The conversion fails while checking the latest kernel version if any of the repositories enabled on the system is not accessible. ([JIRA:RHELC-689](https://issues.redhat.com/browse/RHELC-689))

It was fixed in #557
